---
assembly: hg38
build_author: ec2-user
build_date: 2017-11-22T00:11:00
chromosomes:
- chr1
- chr2
- chr3
- chr4
- chr5
- chr6
- chr7
- chr8
- chr9
- chr10
- chr11
- chr12
- chr13
- chr14
- chr15
- chr16
- chr17
- chr18
- chr19
- chr20
- chr21
- chr22
- chrM
- chrX
- chrY
database_dir: '~'
files: '~'
files_dir: /mnt/db_backup/hg38/
snpProcessor: bystro-snp
statistics:
  dbSNPnameField: dbSNP.name
  exonicAlleleFunctionField: refSeq.exonicAlleleFunction
  outputExtensions:
    json: .statistics.json
    qc: .statistics.qc.tab
    tab: .statistics.tab
  programPath: bystro-stats
  refTrackField: ref
  siteTypeField: refSeq.siteType
temp_dir: '~'
tracks:
- name: ref
  remote_dir: http://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/
  remote_files:
  - chr1.fa.gz
  - chr2.fa.gz
  - chr3.fa.gz
  - chr4.fa.gz
  - chr5.fa.gz
  - chr6.fa.gz
  - chr7.fa.gz
  - chr8.fa.gz
  - chr9.fa.gz
  - chr10.fa.gz
  - chr11.fa.gz
  - chr12.fa.gz
  - chr13.fa.gz
  - chr14.fa.gz
  - chr15.fa.gz
  - chr16.fa.gz
  - chr17.fa.gz
  - chr18.fa.gz
  - chr19.fa.gz
  - chr20.fa.gz
  - chr21.fa.gz
  - chr22.fa.gz
  - chrM.fa.gz
  - chrX.fa.gz
  - chrY.fa.gz
  type: reference
- build_author: ec2-user
  build_date: 2017-11-22T00:11:00
  features:
  - kgID
  - mRNA
  - spID
  - spDisplayID
  - protAcc
  - description
  - rfamAcc
  - name
  - name2
  - dbnsfp.ExAC_pLI: number(3)
  - dbnsfp.ExAC_pRec: number(3)
  - dbnsfp.ExAC_pNull: number(3)
  - dbnsfp.LoFtool_score: number(3)
  - dbnsfp.ExAC_nonTCGA_pRec: number(3)
  - dbnsfp.ExAC_nonTCGA_pNull: number(3)
  - dbnsfp.ExAC_nonTCGA_pLI: number(3)
  - dbnsfp.ExAC_nonpsych_pRec: number(3)
  - dbnsfp.ExAC_nonpsych_pNull: number(3)
  - dbnsfp.ExAC_nonpsych_pLI: number(3)
  fetch_date: 2017-11-21T18:26:00
  join:
    features:
    - alleleID
    - phenotypeList
    - clinicalSignificance
    - type
    - origin
    - numberSubmitters
    - reviewStatus
    - chromStart
    - chromEnd
    track: clinvar
  local_files:
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr5.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr6.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr8.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr2.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr7.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr4.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr3.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr1.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr15.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr13.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr14.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr11.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr16.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr9.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr10.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr12.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr22.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr20.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr17.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr18.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chrX.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr21.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chr19.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chrM.with_dbnsfp.gz
  - /mnt/db_backup/hg38/refSeq/hg38.refGene.chrY.with_dbnsfp.gz
  name: refSeq
  nearest:
  - name
  - name2
  nearestTss:
  - name
  - name2
  refGeneXdbnsfp_date: 2017-11-21T18:28:00
  sql_statement: SELECT refGene.name, chrom, strand, txStart, txEnd, cdsStart, cdsEnd,
    exonCount, exonStarts, exonEnds, score, name2, kgID, mRNA, spID, spDisplayID,
    refseq, protAcc, description, rfamAcc, tRnaName, value AS 'ensemblID', geneSymbol
    FROM refGene LEFT JOIN hg38.kgXref k ON refGene.name = k.refseq LEFT JOIN hg38.knownToEnsembl
    e ON k.kgID = e.name
  type: gene
  utils:
  - name: fetch
  - args:
      geneFile: /mnt/db_backup/dbnsfp/dbNSFP3.5_gene.complete
    name: refGeneXdbnsfp
  version: 11
- name: phastCons
  remote_dir: http://hgdownload.cse.ucsc.edu/goldenPath/hg38/phastCons100way/hg38.100way.phastCons/
  remote_files:
  - chr1.phastCons100way.wigFix.gz
  - chr2.phastCons100way.wigFix.gz
  - chr3.phastCons100way.wigFix.gz
  - chr4.phastCons100way.wigFix.gz
  - chr5.phastCons100way.wigFix.gz
  - chr6.phastCons100way.wigFix.gz
  - chr7.phastCons100way.wigFix.gz
  - chr8.phastCons100way.wigFix.gz
  - chr9.phastCons100way.wigFix.gz
  - chr10.phastCons100way.wigFix.gz
  - chr11.phastCons100way.wigFix.gz
  - chr12.phastCons100way.wigFix.gz
  - chr13.phastCons100way.wigFix.gz
  - chr14.phastCons100way.wigFix.gz
  - chr15.phastCons100way.wigFix.gz
  - chr16.phastCons100way.wigFix.gz
  - chr17.phastCons100way.wigFix.gz
  - chr18.phastCons100way.wigFix.gz
  - chr19.phastCons100way.wigFix.gz
  - chr20.phastCons100way.wigFix.gz
  - chr21.phastCons100way.wigFix.gz
  - chr22.phastCons100way.wigFix.gz
  - chrX.phastCons100way.wigFix.gz
  - chrY.phastCons100way.wigFix.gz
  - chrM.phastCons100way.wigFix.gz
  type: score
- name: phyloP
  remote_dir: http://hgdownload.cse.ucsc.edu/goldenPath/hg38/phyloP100way/hg38.100way.phyloP100way/
  remote_files:
  - chr1.phyloP100way.wigFix.gz
  - chr2.phyloP100way.wigFix.gz
  - chr3.phyloP100way.wigFix.gz
  - chr4.phyloP100way.wigFix.gz
  - chr5.phyloP100way.wigFix.gz
  - chr6.phyloP100way.wigFix.gz
  - chr7.phyloP100way.wigFix.gz
  - chr8.phyloP100way.wigFix.gz
  - chr9.phyloP100way.wigFix.gz
  - chr10.phyloP100way.wigFix.gz
  - chr11.phyloP100way.wigFix.gz
  - chr12.phyloP100way.wigFix.gz
  - chr13.phyloP100way.wigFix.gz
  - chr14.phyloP100way.wigFix.gz
  - chr15.phyloP100way.wigFix.gz
  - chr16.phyloP100way.wigFix.gz
  - chr17.phyloP100way.wigFix.gz
  - chr18.phyloP100way.wigFix.gz
  - chr19.phyloP100way.wigFix.gz
  - chr20.phyloP100way.wigFix.gz
  - chr21.phyloP100way.wigFix.gz
  - chr22.phyloP100way.wigFix.gz
  - chrX.phyloP100way.wigFix.gz
  - chrY.phyloP100way.wigFix.gz
  - chrM.phyloP100way.wigFix.gz
  type: score
- build_date: 2017-04-22T05:22:00
  caddToBed_date: 2017-01-19T04:37:00
  filterCadd_date: 2017-08-28T18:28:00
  local_files:
  - whole_genome_SNVs.tsv.bed.mapped.chr19.organized-by-chr.txt.sorted.chr19.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr18.organized-by-chr.txt.sorted.chr18.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr17.organized-by-chr.txt.sorted.chr17.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr16.organized-by-chr.txt.sorted.chr16.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr15.organized-by-chr.txt.sorted.chr15.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr14.organized-by-chr.txt.sorted.chr14.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr13.organized-by-chr.txt.sorted.chr13.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr21.organized-by-chr.txt.sorted.chr21.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr22.organized-by-chr.txt.sorted.chr22.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr20.organized-by-chr.txt.sorted.chr20.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr10.organized-by-chr.txt.sorted.chr10.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr12.organized-by-chr.txt.sorted.chr12.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr11.organized-by-chr.txt.sorted.chr11.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.chrM.organized-by-chr.chrM.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chrY.organized-by-chr.txt.sorted.chrY.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr1.organized-by-chr.txt.sorted.chr1.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr9.organized-by-chr.txt.sorted.chr9.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr2.organized-by-chr.txt.sorted.chr2.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr8.organized-by-chr.txt.sorted.chr8.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr6.organized-by-chr.txt.sorted.chr6.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr7.organized-by-chr.txt.sorted.chr7.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr5.organized-by-chr.txt.sorted.chr5.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr4.organized-by-chr.txt.sorted.chr4.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chr3.organized-by-chr.txt.sorted.chr3.filtered.txt.gz
  - whole_genome_SNVs.tsv.bed.mapped.chrX.organized-by-chr.txt.sorted.chrX.filtered.txt.gz
  name: cadd
  sortCadd_date: 2017-01-20T23:53:00
  sorted_guaranteed: 1
  type: cadd
- build_field_transformations:
    alleleFreqs: split [,]
    alleleNs: split [,]
    alleles: split [,]
    func: split [,]
    observed: split [\/]
  features:
  - name
  - strand
  - observed
  - class
  - func
  - alleles
  - alleleNs: number
  - alleleFreqs: number(2)
  name: dbSNP
  sql_statement: SELECT * FROM hg38.snp147
  type: sparse
- based: 1
  build_field_transformations:
    chrom: chr .
    clinicalSignificance: split [;]
    origin: split [;]
    phenotypeList: split [;]
    reviewStatus: split [;]
    type: split [;]
  build_row_filters:
    Assembly: == GRCh38
  features:
  - alleleID: number
  - phenotypeList
  - clinicalSignificance
  - type
  - origin
  - numberSubmitters: number(2)
  - reviewStatus
  - referenceAllele
  - alternateAllele
  fieldMap:
    '#AlleleID': alleleID
    AlternateAllele: alternateAllele
    Chromosome: chrom
    ClinicalSignificance: clinicalSignificance
    NumberSubmitters: numberSubmitters
    Origin: origin
    PhenotypeList: phenotypeList
    ReferenceAllele: referenceAllele
    ReviewStatus: reviewStatus
    Start: chromStart
    Stop: chromEnd
    Type: type
  local_files:
  - variant_summary.txt.gz
  name: clinvar
  remote_files:
  - ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/variant_summary.txt.gz
  type: sparse
- build_author: ec2-user
  build_date: 2017-08-29T17:10:00
  build_row_filters:
    AS_FilterStatus: == PASS
  features:
  - alt
  - id
  - trTv: number(2)
  - af: number(2)
  - an: number(2)
  - an_afr: number(2)
  - an_amr: number(2)
  - an_asj: number(2)
  - an_eas: number(2)
  - an_fin: number(2)
  - an_nfe: number(2)
  - an_oth: number(2)
  - an_male: number(2)
  - an_female: number(2)
  - af_afr: number(2)
  - af_amr: number(2)
  - af_asj: number(2)
  - af_eas: number(2)
  - af_fin: number(2)
  - af_nfe: number(2)
  - af_oth: number(2)
  - af_male: number(2)
  - af_female: number(2)
  fieldMap:
    AF: af
    AF_AFR: af_afr
    AF_AMR: af_amr
    AF_ASJ: af_asj
    AF_EAS: af_eas
    AF_FIN: af_fin
    AF_Female: af_female
    AF_Male: af_male
    AF_NFE: af_nfe
    AF_OTH: af_oth
    AN: an
    AN_AFR: an_afr
    AN_AMR: an_amr
    AN_ASJ: an_asj
    AN_EAS: an_eas
    AN_FIN: an_fin
    AN_Female: an_female
    AN_Male: an_male
    AN_NFE: an_nfe
    AN_OTH: an_oth
  local_files:
  - gnomad.genomes.r2.0.1.sites.*.liftedOver.hg38.vcf.liftedOver.gz
  name: gnomad.genomes
  type: vcf
  version: 1
- build_author: ec2-user
  build_date: 2017-08-29T17:10:00
  build_row_filters:
    AS_FilterStatus: == PASS
  features:
  - alt
  - id
  - trTv: number(2)
  - af: number(2)
  - an: number(2)
  - an_afr: number(2)
  - an_amr: number(2)
  - an_asj: number(2)
  - an_eas: number(2)
  - an_fin: number(2)
  - an_nfe: number(2)
  - an_oth: number(2)
  - an_male: number(2)
  - an_female: number(2)
  - af_afr: number(2)
  - af_amr: number(2)
  - af_asj: number(2)
  - af_eas: number(2)
  - af_fin: number(2)
  - af_nfe: number(2)
  - af_oth: number(2)
  - af_male: number(2)
  - af_female: number(2)
  fieldMap:
    AF: af
    AF_AFR: af_afr
    AF_AMR: af_amr
    AF_ASJ: af_asj
    AF_EAS: af_eas
    AF_FIN: af_fin
    AF_Female: af_female
    AF_Male: af_male
    AF_NFE: af_nfe
    AF_OTH: af_oth
    AN: an
    AN_AFR: an_afr
    AN_AMR: an_amr
    AN_ASJ: an_asj
    AN_EAS: an_eas
    AN_FIN: an_fin
    AN_Female: an_female
    AN_Male: an_male
    AN_NFE: an_nfe
    AN_OTH: an_oth
  local_files:
  - gnomad.exomes.r2.0.1.sites.liftedOver.hg38.vcf.liftedOver.gz
  name: gnomad.exomes
  type: vcf
  version: 1
vcfProcessor: bystro-vcf
version: 85

